# ==========================================
# base/kustomization.yaml
# 공통 Kubernetes 리소스 정의
# ==========================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- k8s.yaml
images:
- name: resttemplateserver-sep
  newName: 210.90.24.172:8080/project-sep/leeyoungkon/resttemplateserver-sep
  newTag: 13820d1f75a8c125c0a3afd6520f42162385aca1
